#:kivy 2.0
              
<GraphScreen>:
    BoxLayout:
        id: box
        size_hint: None, None
        size: 1004, 200
        pos: 10, 390
        
    BoxLayout:
        size_hint: None, None
        size: 100, 50
        pos: 914, 10
        Button:
            text: 'Back to menu'
            
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'menu'